# Generated by Django 5.0.6 on 2026-09-08 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_certificate_semester_certificate_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_number', models.PositiveSmallIntegerField(help_text='1, 2, or 3 (maximum 3 unique hints per question)')),
                ('hint_text', models.TextField()),
                ('hint_type', models.CharField(default='local_llm', help_text='local_llm or diagnostic', max_length=32)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hints', to='core.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_hints', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hints', to='core.submission')),
            ],
            options={
                'ordering': ['hint_number'],
                'unique_together': {('student', 'question', 'hint_number')},
            },
        ),
    ]
