# Generated by Django 5.0.6 on 2026-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_subquestion_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subquestion',
            options={'ordering': ['main_question__title', 'type']},
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
