# Generated by Django 5.0.6 on 2026-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_subquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(default='Option A', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(default='Option B', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(default='Option C', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(default='Option D', max_length=255),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text',
            field=models.TextField(default='Question text'),
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question',
        ),
    ]
