# Generated by Django 5.0.6 on 2026-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_quiz_passing_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('cert_eligible', 'Student Certificate Eligible'), ('cert_faculty_request', 'Faculty Sent Approval Request'), ('cert_hod_approved', 'HoD Approved Certificate'), ('cert_hod_rejected', 'HoD Rejected Certificate'), ('faculty_note', 'Message from Faculty'), ('quiz_alert', 'New Quiz Available')], max_length=32),
        ),
    ]
